name: alura-php-mvc

services:
  apache:
    build:
      context: docker/apache
      args:
        PHP_VERSION: 8.4
    volumes:
      - type: bind
        source: .
        target: /app/
    ports:
      - name: web
        target: 80
        published: "8081"
        protocol: tcp
        app_protocol: http
        mode: host

  nginx:
    build:
      context: docker/nginx
    volumes:
      - type: bind
        source: .
        target: /app
      - type: bind
        source: docker/nginx/default.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - name: web
        target: 80
        published: "8082"
        protocol: tcp
        app_protocol: http
        mode: host

  php-fpm:
    build:
      context: docker/php-fpm
      args:
        PHP_VERSION: 8.4
    volumes:
      - type: bind
        source: .
        target: /app

  database:
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    image: mariadb:noble
    environment:
      MARIADB_DATABASE: aluraplay
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - type: volume
        source: mariadb_data
        target: /var/lib/mysql
      - type: bind
        source: docker/db.sql
        target: /docker-entrypoint-initdb.d/db.sql
    ports:
      - name: mysql
        target: 3306
        published: "3306"
        mode: host

volumes:
  mariadb_data:
